### ISSUE TITLE
why xcom api only provide read api without write api?

### ISSUE THREAD

**Issue by foreverseer** [apache/airflow-client-python#108]
use xcom to add info to task is very common, but only read api in this lib, with out write api
![image](https://github.com/apache/airflow-client-python/assets/24448028/ece88f7e-466a-43c4-bbe5-47d8f27705c9)

**Comment by potiuk** [comment]
XCom is written by tasks. If you want to add a new feature of "simulating" what tasks are doing, that's likely a big new feature that should be proposed and discussed on devlist.
