### ISSUE TITLE
Trouble to access reason behind Failed DAGs LOG 

### ISSUE THREAD

**Issue by Meghsham-Jambhulkar** [apache/airflow-client-python#109]
Hello , Currently i am working on a task where i have to generate  logs of success and failed DAGs 

With help of following code I am able to get DAG details about success DAGs I am able to get DAG_ids , Start_date , end_date ,state all 
necessary things for a DAG only part I am stuck at is getting reason why a DAG failed 
I have used following list of functions to help me reach here 
- get_dag_runs
- get_dag_runs_batch
- get_dag_run
- get_task_instances

If any solutions please let me know

**Comment by potiuk** [comment]
You should anly use REST API. You should get familiar with it. Calling internal methods of objects in Python is not part of the public interface of Airflow https://airflow.apache.org/docs/apache-airflow/stable/public-airflow-interface.html and if you rely on it, it will break.

**Comment by Meghsham-Jambhulkar** [comment]
@potiuk 
First of all Thank you for you input I am currently using these methods and they are working as expected , Its just the issue is when i am working on Failed DAGs I do not find a way to load error message for failed dags

**Comment by potiuk** [comment]
I guess - tou should read logs and guess itfrom there. There is not a single reason for failure, you must use what is available in logs.

**Comment by potiuk** [comment]
I see you opened https://github.com/apache/airflow-client-python/issues/110 -> you need to look at your airflow's logging configuration if you have troubles retrieving your logs. But it's not Python client's issue
