### ISSUE TITLE
Official Documentation error (Readme)

### ISSUE THREAD

**Issue by Al4DIN** [apache/airflow-client-python#119]
Hello,
I was trying to example on the `Readme.md `, but it looks like it has an error with the code on the **[Getting-started](https://github.com/apache/airflow-client-python?tab=readme-ov-file#getting-started)**
`import airflow_client.client` , when we try to create our client it render an error with client isn't defined.
To correct it should be , `from airflow_client import client`

**Comment by pierrejeambrun** [comment]
Hello @Al4DIN,

Thank you for reporting the issue.

Maybe you can open a PR to fix that ? I'm sure that would be really helpful for other users, and a great way to contribute back for this free software :)

**Comment by Al4DIN** [comment]
Thank you @pierrejeambrun.
Yes, I'll do that.

**Comment by Al4DIN** [comment]
#120
