### ISSUE TITLE
Get DAG Run API Docs error

### ISSUE THREAD

**Issue by gontxomde** [apache/airflow-client-python#121]
In the docs of the api (https://airflow.apache.org/docs/apache-airflow/stable/stable-rest-api-ref.html#operation/get_dag_run) the example in the right shows a "queued" execution with a end_date not null. is this behaviour real? I assume the end_date will only be populated when state is either "success" or "failed"

**Comment by pierrejeambrun** [comment]
Those are just auto generated examples based on the fields type. There is no consistency enforced in there for field values compared to each other or that the example should represent an actual business case.

It just happens that the `queued` state is the first one in the `enum` and most likely was used to populate the example.

Closing, feel free to reopen if you have more questions.
