### ISSUE TITLE
trigger dag api is broken

### ISSUE THREAD

**Issue by msumit** [apache/airflow-client-python#21]
Client version: 2.1.0

Code:
```
    dag_id = "example_bash_operator"
    dag_run_api_instance = dag_run_api.DAGRunApi(api_client)
    try:
        # Create a DAGRun object
        dag_run = DAGRun(
            dag_run_id='some_test_run',
            dag_id=dag_id,
            external_trigger=True,
        )
        api_response = dag_run_api_instance.post_dag_run(dag_id, dag_run)
        pprint(api_response)
    except airflow_client.client.exceptions.OpenApiException as e:
        print("Exception when calling DAGRunAPI->post_dag_run: %s\n" % e)
```

Error:
```
HTTP response body: {
  "detail": "Property is read-only - 'dag_id'",
  "status": 400,
  "title": "Bad Request",
  "type": "http://apache-airflow-docs.s3-website.eu-central-1.amazonaws.com/docs/apache-airflow/latest/stable-rest-api-ref.html#section/Errors/BadRequest"
}
```

**Comment by fanqingsong** [comment]
I encountered the same problem.
and I found the test case (airflow_client/test/test_dag_run_api.py) is just shell, with empty test function. 
so I think the quality cannot be assured currently.
mybe using raw REST API is a good choice.

**Comment by zjaxxon** [comment]
Same problem. It seems you must provide a dag_id to initialize a DAGRun while it gives this read-only error in post_dag_run.

**Comment by christhekeele** [comment]
I have worked around this by re-generating the api client for airflow 2.3.0 with [this patch](https://github.com/apache/airflow/pull/19155) applied. Available from [my fork](https://github.com/christhekeele/airflow-client-python/tree/2.3.0). You can install it in a requirements.txt via:

```
# apache-airflow-client==2.1.0
-e git://github.com/christhekeele/airflow-client-python.git@2.3.0#egg=apache-airflow-client
```

**Comment by sureshdsk** [comment]
Is there any alternate way to trigger task without this client?

**Comment by hterik** [comment]
> Is there any alternate way to trigger task without this client?

https://airflow.apache.org/docs/apache-airflow/2.2.4/stable-rest-api-ref.html

**Comment by sureshdsk** [comment]
POST /api/v1/dags/{dag_id}/dagRuns
```
{
  "conf": {},
  "dag_run_id": "test-1",
  "logical_date": "2022-05-25T07:12:59.305Z",
  "state": "queued"
}
```
results in below error.
```
{
    "detail": "Property is read-only - 'state'",
    "status": 400,
    "title": "Bad Request",
    "type": "https://airflow.apache.org/docs/apache-airflow/2.2.3/stable-rest-api-ref.html#section/Errors/BadRequest"
}
```

without "state" param in the payload works 👍

**Comment by VeereshPatil** [comment]
you can not pass **dag_id** and **external_trigger**  as part of DagRun ( dag_id is passed in post_dag_run() function)
The following worked for me,

```
dag_run = DAGRun(
            dag_run_id='some_test_run',
            conf={"key":"values"}
            )
api_response = dag_run_api_instance.post_dag_run(dag_id, dag_run)
```

**Comment by pierrejeambrun** [comment]
`dag_id`, `state` and `external_trigger` are now read only. They should not be provided in the `DagRun` object. With the latest client (2.5.1) we can trigger dag runs like this:

```python
    # DagRun
    dag_run_api_instance = dag_run_api.DAGRunApi(api_client)
    try:
        api_response = dag_run_api_instance.post_dag_run(
            "25616-bug", dag_run_api.DAGRun(dag_run_id="run_from_python_api_client")
        )
        pprint(api_response)
    except airflow_client.client.OpenApiException as e:
        print("Exception when calling DagRunApi->post_dag_run: %s\n" % e)
```
![image](https://user-images.githubusercontent.com/14861206/221316351-10b441a4-7be9-42c6-94c4-27d3608fc9dc.png)

Closing for now, feel free to reopen if needed.
