### ISSUE TITLE
Update with new Airflow 2.2 APIs

### ISSUE THREAD

**Issue by joshzana** [apache/airflow-client-python#32]
Airflow 2.2 has a variety of new APIs: https://airflow.apache.org/docs/apache-airflow/stable/changelog.html#airflow-2-2-0-2021-10-11

In particular, I am interested in the ability to delete a DAG through the API.

The latest version of this library is 2.1.0, and does not have the new methods.

It would be great to see an update!

**Comment by christhekeele** [comment]
Note that this should fix #4 which in turn will fix #21.

**Comment by eladkal** [comment]
was addressed in newer version https://github.com/apache/airflow-client-python/pull/48/files
