### ISSUE TITLE
Is the issues still under monitoring?

### ISSUE THREAD

**Issue by lidh15** [apache/airflow-client-python#35]
It seems that the codes on master branch are no longer updated since 5 months ago and the issues 20 21 27 28 29 are all keeping open though openapi had released 5.2.0 in August and even 5.3.0 recently.

**Comment by lidh15** [comment]
or at least suggest a stable version combination for the library and it's requirements

**Comment by msumit** [comment]
Hi @lidh15, I'm planning to cut a new release (2.2.0) soon. Prolly that would resolve some of these issues.

**Comment by lidh15** [comment]
> Hi @lidh15, I'm planning to cut a new release (2.2.0) soon. Prolly that would resolve some of these issues. 

Thank you very much, I'm looking forward to the new release. When will it be released?

**Comment by msumit** [comment]
Need to get this https://github.com/apache/airflow/pull/19155 merged first.
