### ISSUE TITLE
Error - "certificate verify failed - unable to get local issuer certificate" while using airflow_client

### ISSUE THREAD

**Issue by amuley11** [apache/airflow-client-python#45]
I'm getting an error- "certificate verify failed - unable to get local issuer certificate" while using airflow_client. Could someone please provide a resolution for it?

**Comment by gyscos** [comment]
Many python HTTP clients use requests, and setting `REQUESTS_CA_BUNDLE` is often enough to make it use the system certificates.

It doesn't seem to work for this library though, what's the way to make it use system certificates?
