### ISSUE TITLE
Bug: `DAGApi.get_dag_details` fails if `DAG Run Timeout` is `None`

### ISSUE THREAD

**Issue by thejohnbackes** [apache/airflow-client-python#52]
Observed Behavior:

`DAGApi.get_dag_details` fails if `DAG Run Timeout` is `None`.

To recreate:

First, Create a DAG and set "DAG Run Timout" as None
Next, try to access the DAG Details using the API:

```
    api = DAGApi(airflow_client.client)
    dag = api.get_dag_details(dag_id)
```

Exception:

```
airflow_client.client.exceptions.ApiTypeError: Invalid type for variable 'dag_run_timeout'. Required value type is TimeDelta and passed type was NoneType at ['received_data']['dag_run_timeout']
```

Proposed fix:

The [DAG schema](https://github.com/apache/airflow-client-python/blob/3547adf28757f05544d6308157a9ae5c95c03e81/airflow_client/client/model/dag_detail_all_of.py#L113) at `dagrun_timeout` should support NoneType, as [this is what is supported in the Airflow API documentation](https://airflow.apache.org/docs/apache-airflow/stable/_api/airflow/models/dag/index.html#:~:text=active%20DAG%20runs-,dagrun_timeout,-(timedelta%20%7C%20None)%20%E2%80%93%20specify).

**Comment by potiuk** [comment]
Yep. Would be nice if someone grabs it anf fixes it.

**Comment by DavidKatz-il** [comment]
I'm getting the following error:
```
airflow_client.client.exceptions.ApiTypeError: Invalid type for variable 'execution_timeout'. Required value type is TimeDelta and passed type was NoneType at ['received_data']['tasks'][0]['execution_timeout']
```
when using `api.get_task(dag_id, task_id)` or `api.get_tasks(dag_id)`
