### ISSUE TITLE
Basic authentication stopped working in 2.5.0

### ISSUE THREAD

**Issue by maciejmochol** [apache/airflow-client-python#61]
Hello,

Version 2.5.0 of the client library stopped generating Authorization header when sending HTTP requests to Airflow.
I did some debug of the code and I can see that eg. for ConfigApi, a code that previously looked like this:
```
class ConfigApi(object):
    """NOTE: This class is auto generated by OpenAPI Generator
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    def __init__(self, api_client=None):
        if api_client is None:
            api_client = ApiClient()
        self.api_client = api_client
        self.get_config_endpoint = _Endpoint(
            settings={
                'response_type': (Config,),
                'auth': [
                    'Basic',
                    'Kerberos'
                ],
```
now looks like this

```
class ConfigApi(object):
    """NOTE: This class is auto generated by OpenAPI Generator
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    def __init__(self, api_client=None):
        if api_client is None:
            api_client = ApiClient()
        self.api_client = api_client
        self.get_config_endpoint = _Endpoint(
            settings={
                'response_type': (Config,),
                'auth': [],
```

Are we doing something wrong?

**Comment by potiuk** [comment]
Hey @pierrejeambrun @ephraimbuddy - I confirm this is a problem. 

I looked at possible issues and I think simply the client was generated without following this step from the release process (or somehow an unedited version of the api specification has been used:

> Edit the file airflow/airflow/api_connexion/openapi/v1.yaml Make sure it has the following securitySchemas listed under security section
> 
> security:
>   - Basic: []
>   - GoogleOpenId: []
>   - Kerberos: []

(This calls even more for full automation of the release process if confirmed - as discussed few days ago).

**Comment by pierrejeambrun** [comment]
:cry: I don't know how I missed that, I am going to start working on 2.5.1 to fix this.

Dumb question but why do we add this just for client generation purpose ? Could it be added to the `v1.yaml` spec to properly describe the supported authorizations ?

**Comment by potiuk** [comment]
> cry I don't know how I missed that, I am going to start working on 2.5.1 to fix this.
> 
> Dumb question but why do we add this just for client generation purpose ? Could it be added to the `v1.yaml` spec to properly describe the supported authorizations ?
> 
> edit: Got it, just found [apache/airflow#17174](https://github.com/apache/airflow/pull/17174)

Yeah. I think we need to leave freedom for those who build the client on their own (though I find it a bit odd choice to add supported authentication in the API specs - those seem pretty orthogonal and I would rather expect to specify authentication mechanisms as generator parameter).

I think automating it in our release process (How about `breeze release-management build-python-client` ?)

**Comment by potiuk** [comment]
(and we will need to yank 2.5.0 once we release 2.5.1 I think )

**Comment by maciejmochol** [comment]
Many thanks for your answers

**Comment by pierrejeambrun** [comment]
@maciejmochol closing as 2.5.1 has just been released with a fix for the authentication issue you encountered.

2.5.0 has also been removed from the version listing of the package index. This way you never get this version when installing the package unless you explicitly target it (i.e `==2.5.0`).

**Comment by maciejmochol** [comment]
@pierrejeambrun great, many thanks

**Comment by potiuk** [comment]
🎉 🎉 🎉 🎉 🎉
